#%RAML 1.0 NamedExample
value:
-
  name: "Kerosene" 
  category: "Fuel"
  sector: "Energy" 
  source: "EXIOBASE"
  uncertainty: string
  year: "2021"
  region: "ROW_WF"
  region_name: "Africa except Egypt and South Africa"
  description: "Emission intensity of supply chain in EUR spend on: kerosene. Retrieved from the EXIOBASE v3 model outputs for products. These factors were calculated based on 2019 data. CO2 equivalent factors incorporate emissions from land use; constituent gases have not been included as they do not. The LCA boundaries of these factors are not defined by the source. These factors include effects of international trade."
  unit_type:
      type: "Money"
  factor: 2.0191
  factor_calculation_method: "ar5"
  factor_calculation_origin: "source"
  