#%RAML 1.0 NamedExample
value:
-
  name: "Light-Duty Truck" 
  category: "Vehicles"
  sector: "Transport" 
  source: "EPA"
  uncertainty: string
  year: "2021"
  region: "US"
  region_name: "United States"
  description: "Emission intensity of light duty truck (includes full-size pickup trucks/full-size vans/extended-length SUVs with wheelbase greater than 121 inches). Retrieved from the EPA's GHG Emission Factors Hub (xlsx)."
  unit_type:
      type: "Distance"
  factor: 0.466986
  factor_calculation_method: "ar5"
  factor_calculation_origin: "climatiq"